_side = [_this, 0, "left"] call bis_fnc_param;
if(count DYN_RACE_CARDESIGN_SELECTED_CUSTOMIZATION == 0) exitWith {};

_selectedPart = DYN_RACE_CARDESIGN_SELECTED_CUSTOMIZATION select 0;
if(_side == "left") then
{
	DYN_RACE_SELECTED_CUSTOMIZATIONID = DYN_RACE_SELECTED_CUSTOMIZATIONID - 1;
}
else
{
	DYN_RACE_SELECTED_CUSTOMIZATIONID = DYN_RACE_SELECTED_CUSTOMIZATIONID + 1;
};

if(DYN_RACE_SELECTED_CUSTOMIZATIONID < 0) then {DYN_RACE_SELECTED_CUSTOMIZATIONID = count (DYN_RACE_CARDESIGN_CUSTOMIZATIONS)  - 1};
if(DYN_RACE_SELECTED_CUSTOMIZATIONID > count (DYN_RACE_CARDESIGN_CUSTOMIZATIONS)  - 1) then {DYN_RACE_SELECTED_CUSTOMIZATIONID = 0};

DYN_RACE_CARDESIGN_SELECTED_CUSTOMIZATION = DYN_RACE_CARDESIGN_CUSTOMIZATIONS select DYN_RACE_SELECTED_CUSTOMIZATIONID;
//[] call DYN_fnc_CarDesignFocusOnSelectedPart;